apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  replicas: 1
  schedulerName: PAVA
  containers:
  - name: redis
    image: redis
    imagePullPolicy: IfNotPresent
    resources:
        limits:
                cpu: "1"
        requests:
                cpu: 500m
  priorityClassName: high-priority
