apiVersion: v1
kind: Pod
metadata:
  name: pod5
spec:
  
  containers:
  - name: redis
    image: redis
    imagePullPolicy: IfNotPresent
    resources:
        limits:
                cpu: "1"
        requests:
                cpu: 500m
